### ISSUE TITLE
BUG: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [rudderlabs/rudder-transformer#2573]
**Describe the bug**
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

**To Reproduce**
Scroll to bottom and see twitter logo

**Expected behavior**
Twitter logo should be changed to X.

**Screenshots**
<img width="960" alt="Screenshot 2023-09-08 170024" src="https://github.com/rudderlabs/rudder-transformer/assets/91591901/8ece6c9b-4f8f-42d1-840e-3b7547aae604">

**Additional context**
@gmathieu 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by lalitkumawat1m** [comment]
@ItsSudip, @krishna2020, @sandeepdsvs,@shrouti1507,

I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by ItsSudip** [comment]
@lalitkumawat1m Thank you for pointing this out. Unfortunately, this part is not in the scope of this repository and the other repository where we maintain frontend-related things is not open source. I will let our design team know about this.

**Comment by gitcommitshow** [comment]
Thank you @lalitkumawat1m for pitching in to contribute. This issue report is helpful.
In order to contribute to RudderStack Open Source projects, please consider developing a new integration or improving existing integrations. [This guide](https://www.rudderstack.com/docs/user-guides/how-to-guides/developing-integrations-for-rudderstack/) will be handy.
