### ISSUE TITLE
Several missing feature in Amplitude

### ISSUE THREAD

**Issue by lxcid** [rudderlabs/rudder-transformer#317]
## enable web attribution captured in `context.campaign.*` in amplitude

- https://github.com/rudderlabs/rudder-transformer/blob/master/v0/destinations/am/data/AmplitudePageConfig.json
- https://segment.com/docs/connections/spec/common/#context-fields-automatically-collected

![Screen Shot 2020-09-25 at 7 30 12 PM](https://user-images.githubusercontent.com/297156/94262134-92544f00-ff65-11ea-8425-dda4f7ec4d7b.png)

## enable `Analytics.group()` to map to Amplitude's Account

- Group identify API: https://help.amplitude.com/hc/en-us/articles/115001765532#group-identify-api
- map `context.groupId` to group properties?

**Comment by sayan-mitra** [comment]
Thanks for reaching out!

Following is the snapshot on AM dashboard after the below proposed changes for:
-  forwarding campaign related information on using RudderStack page calls (initial campaign info and otherwise) 
-  Attaching user to group on using RudderStack group calls (RudderStack config UI will have inputs to identify group type and group name). **_For ex:  rudderanalytics.group('id', {groupType: "orgId", groupName: 15, company: "TEST_Comp"})_ will attach the user to groupType: **orgId** and groupName: **15**  if groupType and groupName are the config UI inputs.
-  populate group properties on using RudderStack group calls (RudderStack config UI will have inputs to identify group type and group name)  **The above sample call will attach **id**(Rudder group call groupId), and rest Rudder **group call properties** as group properties to groupType: **orgId** and groupName: **15** (https://developers.amplitude.com/docs/group-identify-api).  ** _this is not present in the below snapshot_


Let us know if this fits your expectations.
![Screenshot 2020-09-29 at 4 36 44 PM](https://user-images.githubusercontent.com/3198515/94552003-d603cd00-0273-11eb-8c1a-febebdae0427.png)

**Comment by lxcid** [comment]
@sayan-mitra Thanks! It does looks good.

I want to note that in Segment common fields spec, they uses `context.groupId` to denote group. While for Amplitude, there can be more than 1 type of group.

So for _RudderStack config UI will have inputs to identify group type and group name_, can I suggest that it is dot separated key? For example,

```js
{
  context: {
    groupType: "org_id",
    groupId: "org_123"
  }
}
```

I would like to be able to set through the ui the group type to `context.groupType` and `context.groupId`.

**Comment by lxcid** [comment]
Lastly, Because amplitude tag events through the `groups` property, if there is a way we can provides group properties from our side, that will help a lot, because we might need to set more than 1 group type, which Amplitude support but the rudder stack UI might not be sufficient.
