### ISSUE TITLE
Sending data to Hubspot's forms endpoint

### ISSUE THREAD

**Issue by joesantos418** [rudderlabs/rudder-transformer#381]
We are trying Rudderstack out at our company and one of the integration we need is with Hubspot, but we need to send data to its form endpoint. Should we use the webhook integration with a custom transformer instead?

**Comment by utsabc** [comment]
Hi @joesantos418, could you point me to the exact Hubspot API that you are trying to access so that we can take an initial look into it. Also, you can write [custom transformations](https://www.rudderstack.com/docs/transformations/) over your events and send them over to specific endpoint using webhook destination
